package code;

import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author lenadro
 */
public class NewJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    private String imageFormat = "";
    
    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaUno = new javax.swing.JTabbedPane();
        panelUno = new javax.swing.JPanel();
        lb_nombreInputImagen = new javax.swing.JLabel();
        btn_buscarImagen = new javax.swing.JButton();
        txt_imputmagen = new javax.swing.JTextField();
        chk_png = new javax.swing.JCheckBox();
        chk_jpeg = new javax.swing.JCheckBox();
        chk_gif = new javax.swing.JCheckBox();
        chk_bmp = new javax.swing.JCheckBox();
        chk_tiff = new javax.swing.JCheckBox();
        lb_vistaPrevia = new javax.swing.JLabel();
        lb_nombreOutputImagen = new javax.swing.JLabel();
        txt_nombreImagen = new javax.swing.JTextField();
        btn_guardarImagen = new javax.swing.JButton();
        lb_seGuardaImagen = new javax.swing.JLabel();
        txt_outputImagen = new javax.swing.JTextField();
        btn_buscaRutarImagen = new javax.swing.JButton();
        panelDos = new javax.swing.JPanel();
        panelTres = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_rutaPdf = new javax.swing.JTextField();
        btn_agregarPdf = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_guardarPdf = new javax.swing.JTextField();
        btn_guardarPdf = new javax.swing.JButton();
        btn_acepPdfToPng = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        sp_dpiValue = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_juntarpdfUno = new javax.swing.JTextField();
        btn_agregarPdf1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_juntarpdfDos = new javax.swing.JTextField();
        btn_agregarPdf2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_obtMetadatos = new javax.swing.JButton();
        txt_namePDF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_urlGuardadoPDF = new javax.swing.JTextField();
        btn_guardarPDFcombinado = new javax.swing.JButton();
        btn_agregarUrlGuardado = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAP");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        lb_nombreInputImagen.setText("Imagen:");

        btn_buscarImagen.setText("Buscar");
        btn_buscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarImagenActionPerformed(evt);
            }
        });

        txt_imputmagen.setEditable(false);

        chk_png.setText("Convertir a PNG");
        chk_png.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_pngActionPerformed(evt);
            }
        });

        chk_jpeg.setText("Convertir a JPEG");
        chk_jpeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_jpegActionPerformed(evt);
            }
        });

        chk_gif.setText("Convertir a GIF");
        chk_gif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_gifActionPerformed(evt);
            }
        });

        chk_bmp.setText("Convertir a BMP");
        chk_bmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_bmpActionPerformed(evt);
            }
        });

        chk_tiff.setText("Convertir a TIFF");
        chk_tiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_tiffActionPerformed(evt);
            }
        });

        lb_vistaPrevia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_nombreOutputImagen.setText("Nombre:");

        btn_guardarImagen.setText("Guardar");
        btn_guardarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarImagenActionPerformed(evt);
            }
        });

        lb_seGuardaImagen.setText("Se guarda en:");

        txt_outputImagen.setEditable(false);
        txt_outputImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_outputImagenActionPerformed(evt);
            }
        });

        btn_buscaRutarImagen.setText("Buscar");
        btn_buscaRutarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaRutarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUnoLayout = new javax.swing.GroupLayout(panelUno);
        panelUno.setLayout(panelUnoLayout);
        panelUnoLayout.setHorizontalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelUnoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_seGuardaImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_outputImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscaRutarImagen)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUnoLayout.createSequentialGroup()
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUnoLayout.createSequentialGroup()
                                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk_tiff)
                                    .addComponent(chk_bmp)
                                    .addComponent(chk_gif)
                                    .addComponent(chk_jpeg)
                                    .addComponent(chk_png))
                                .addGap(46, 46, 46)
                                .addComponent(lb_vistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUnoLayout.createSequentialGroup()
                                .addComponent(lb_nombreOutputImagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombreImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_guardarImagen))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUnoLayout.createSequentialGroup()
                                .addComponent(lb_nombreInputImagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_imputmagen, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscarImagen)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelUnoLayout.setVerticalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombreInputImagen)
                    .addComponent(btn_buscarImagen)
                    .addComponent(txt_imputmagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_seGuardaImagen)
                    .addComponent(btn_buscaRutarImagen)
                    .addComponent(txt_outputImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                        .addComponent(chk_png)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_jpeg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_gif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_bmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_tiff))
                    .addComponent(lb_vistaPrevia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombreOutputImagen)
                    .addComponent(txt_nombreImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardarImagen))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        vistaUno.addTab("Imagenes", panelUno);

        javax.swing.GroupLayout panelDosLayout = new javax.swing.GroupLayout(panelDos);
        panelDos.setLayout(panelDosLayout);
        panelDosLayout.setHorizontalGroup(
            panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        panelDosLayout.setVerticalGroup(
            panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        vistaUno.addTab("Audio", panelDos);

        panelTres.setAutoscrolls(true);

        jLabel4.setText("PDFs:");

        txt_rutaPdf.setEditable(false);

        btn_agregarPdf.setText("Agregar");
        btn_agregarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPdfActionPerformed(evt);
            }
        });

        jLabel5.setText("Se guarda en:");

        txt_guardarPdf.setEditable(false);

        btn_guardarPdf.setText("Buscar");
        btn_guardarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarPdfActionPerformed(evt);
            }
        });

        btn_acepPdfToPng.setText("Aceptar");
        btn_acepPdfToPng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acepPdfToPngActionPerformed(evt);
            }
        });

        sp_dpiValue.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)300), Short.valueOf((short)300), Short.valueOf((short)1200), Short.valueOf((short)1)));
        sp_dpiValue.setToolTipText("300 (estandar), 600 (alta), 1200 (muy alta).");

        jLabel1.setText("Calidad (DPI)");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel2.setText("Convertir a imagenes (png)");

        jLabel6.setText("PDF1:");

        txt_juntarpdfUno.setEditable(false);

        btn_agregarPdf1.setText("Agregar");
        btn_agregarPdf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPdf1ActionPerformed(evt);
            }
        });

        jLabel7.setText("PDF2:");

        txt_juntarpdfDos.setEditable(false);

        btn_agregarPdf2.setText("Agregar");
        btn_agregarPdf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPdf2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel3.setText("Combinar PDFs");

        btn_obtMetadatos.setText("Obtener metadatos");
        btn_obtMetadatos.setEnabled(false);
        btn_obtMetadatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_obtMetadatosActionPerformed(evt);
            }
        });

        txt_namePDF.setToolTipText("Nombre del nuevo ducumento");

        jLabel8.setText("Nombre:");

        jLabel9.setText("Guardar en:");

        txt_urlGuardadoPDF.setEditable(false);
        txt_urlGuardadoPDF.setToolTipText("Nombre del nuevo ducumento");

        btn_guardarPDFcombinado.setText("Guardar");
        btn_guardarPDFcombinado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarPDFcombinadoActionPerformed(evt);
            }
        });

        btn_agregarUrlGuardado.setText("Buscar");
        btn_agregarUrlGuardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarUrlGuardadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTresLayout = new javax.swing.GroupLayout(panelTres);
        panelTres.setLayout(panelTresLayout);
        panelTresLayout.setHorizontalGroup(
            panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelTresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTresLayout.createSequentialGroup()
                        .addComponent(btn_acepPdfToPng)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_dpiValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(panelTresLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_juntarpdfUno, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_agregarPdf1))
                    .addComponent(jLabel3)
                    .addGroup(panelTresLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_juntarpdfDos, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_agregarPdf2))
                    .addGroup(panelTresLayout.createSequentialGroup()
                        .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_obtMetadatos)
                            .addComponent(btn_guardarPDFcombinado))
                        .addGap(117, 117, 117)
                        .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTresLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_urlGuardadoPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_agregarUrlGuardado))
                            .addGroup(panelTresLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_namePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTresLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_guardarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_guardarPdf))
                        .addGroup(panelTresLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_rutaPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_agregarPdf)
                            .addGap(45, 45, 45))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panelTresLayout.setVerticalGroup(
            panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btn_agregarPdf)
                    .addComponent(txt_rutaPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_guardarPdf)
                    .addComponent(txt_guardarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_acepPdfToPng)
                    .addComponent(sp_dpiValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_agregarPdf1)
                    .addComponent(txt_juntarpdfUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btn_agregarPdf2)
                    .addComponent(txt_juntarpdfDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_namePDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btn_guardarPDFcombinado))
                .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_urlGuardadoPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btn_agregarUrlGuardado)))
                    .addGroup(panelTresLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_obtMetadatos)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        vistaUno.addTab("PDFs", panelTres);

        getContentPane().add(vistaUno);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_gifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_gifActionPerformed
        if (!chk_gif.isSelected()) {
            imageFormat = "";
        } else {
            chk_png.setSelected(false);
            chk_bmp.setSelected(false);
            chk_jpeg.setSelected(false);
            chk_tiff.setSelected(false);
            imageFormat = "gif";
        }
    }//GEN-LAST:event_chk_gifActionPerformed

    private void chk_bmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_bmpActionPerformed
        if (!chk_bmp.isSelected()) {
            imageFormat = "";
        } else {
            chk_png.setSelected(false);
            chk_gif.setSelected(false);
            chk_jpeg.setSelected(false);
            chk_tiff.setSelected(false);
            imageFormat = "bmp";
        }
    }//GEN-LAST:event_chk_bmpActionPerformed

    private void chk_pngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_pngActionPerformed
        if (!chk_png.isSelected()) {
            imageFormat = "";
        } else {
            chk_gif.setSelected(false);
            chk_bmp.setSelected(false);
            chk_jpeg.setSelected(false);
            chk_tiff.setSelected(false);
            imageFormat = "png";
        }
    }//GEN-LAST:event_chk_pngActionPerformed

    private void chk_jpegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_jpegActionPerformed
        if (!chk_jpeg.isSelected()) {
            imageFormat = "";
        } else {
            chk_png.setSelected(false);
            chk_bmp.setSelected(false);
            chk_gif.setSelected(false);
            chk_tiff.setSelected(false);
            imageFormat = "jpeg";
        }
    }//GEN-LAST:event_chk_jpegActionPerformed

    private void chk_tiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_tiffActionPerformed
        if (!chk_tiff.isSelected()) {
            imageFormat = "";
        } else {
            chk_png.setSelected(false);
            chk_bmp.setSelected(false);
            chk_jpeg.setSelected(false);
            chk_gif.setSelected(false);
            imageFormat = "tiff";
        }
    }//GEN-LAST:event_chk_tiffActionPerformed

    private void btn_buscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarImagenActionPerformed
        JFileChooser buscador = new JFileChooser();
        buscador.setMultiSelectionEnabled(true);
        int selected = buscador.showOpenDialog(null);// Abre el buscador de archivos.
        
        if (selected == 0) {
            txt_imputmagen.setText(buscador.getSelectedFile().getAbsolutePath());
            ImageIcon img = new ImageIcon(txt_imputmagen.getText());
            lb_vistaPrevia.setIcon(img);
        }

    }//GEN-LAST:event_btn_buscarImagenActionPerformed

    private void btn_buscaRutarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaRutarImagenActionPerformed
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selected = buscador.showOpenDialog(null);
        
        if (selected == 0) {
            txt_outputImagen.setText(buscador.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btn_buscaRutarImagenActionPerformed

    private void txt_outputImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_outputImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_outputImagenActionPerformed

    private void btn_guardarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarImagenActionPerformed
        try {
            
            String imageName = txt_nombreImagen.getText();
            ImageConverter imgConverter = new ImageConverter
            (imageName, imageFormat);
            
            String str_imputFile = txt_imputmagen.getText();
            String str_outputFile = txt_outputImagen.getText();
            imgConverter.addSources
            (str_imputFile, str_outputFile);
            
            imgConverter.imgConverter();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar la imagen.");
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_guardarImagenActionPerformed

    private void btn_agregarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPdfActionPerformed
        JFileChooser buscador = new JFileChooser();
        int selected = buscador.showOpenDialog(null);
        
        if (selected == 0) {
        txt_rutaPdf.setText(buscador.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btn_agregarPdfActionPerformed

    private void btn_agregarPdf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPdf1ActionPerformed
        JFileChooser buscador = new JFileChooser();
        int selected = buscador.showOpenDialog(null);
        
        if (selected == 0) {
            txt_juntarpdfUno.setText(buscador.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btn_agregarPdf1ActionPerformed

    private void btn_agregarPdf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPdf2ActionPerformed
        JFileChooser buscador = new JFileChooser();
        int selected = buscador.showOpenDialog(null);
        
        if (selected == 0) {
            txt_juntarpdfDos.setText(buscador.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btn_agregarPdf2ActionPerformed

    private void btn_obtMetadatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_obtMetadatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_obtMetadatosActionPerformed

    private void btn_guardarPDFcombinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarPDFcombinadoActionPerformed
        try {
            PDFData mensajeroPDF = new PDFData(txt_namePDF.getText(), (short) 0);
            String[] files = {txt_juntarpdfUno.getText(), txt_juntarpdfDos.getText()};
            mensajeroPDF.meregePDFs(files, txt_urlGuardadoPDF.getText());
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_guardarPDFcombinadoActionPerformed

    private void btn_agregarUrlGuardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarUrlGuardadoActionPerformed
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selected = buscador.showOpenDialog(null);
        
        if (selected == 0) {
            txt_urlGuardadoPDF.setText(buscador.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btn_agregarUrlGuardadoActionPerformed

    private void btn_guardarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarPdfActionPerformed
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selected = buscador.showOpenDialog(null);
        
        if (selected == 0) {
            txt_guardarPdf.setText(buscador.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btn_guardarPdfActionPerformed

    private void btn_acepPdfToPngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acepPdfToPngActionPerformed
        try {
            PDFData mensajeroPDF = new PDFData("PruebaDeRsolucion", (short) sp_dpiValue.getValue());
            
            mensajeroPDF.pdfToPng(new File(txt_rutaPdf.getText()), txt_guardarPdf.getText());
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_acepPdfToPngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatDarkPurpleIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acepPdfToPng;
    private javax.swing.JButton btn_agregarPdf;
    private javax.swing.JButton btn_agregarPdf1;
    private javax.swing.JButton btn_agregarPdf2;
    private javax.swing.JButton btn_agregarUrlGuardado;
    private javax.swing.JButton btn_buscaRutarImagen;
    private javax.swing.JButton btn_buscarImagen;
    private javax.swing.JButton btn_guardarImagen;
    private javax.swing.JButton btn_guardarPDFcombinado;
    private javax.swing.JButton btn_guardarPdf;
    private javax.swing.JButton btn_obtMetadatos;
    private javax.swing.JCheckBox chk_bmp;
    private javax.swing.JCheckBox chk_gif;
    private javax.swing.JCheckBox chk_jpeg;
    private javax.swing.JCheckBox chk_png;
    private javax.swing.JCheckBox chk_tiff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_nombreInputImagen;
    private javax.swing.JLabel lb_nombreOutputImagen;
    private javax.swing.JLabel lb_seGuardaImagen;
    private javax.swing.JLabel lb_vistaPrevia;
    private javax.swing.JPanel panelDos;
    private javax.swing.JPanel panelTres;
    private javax.swing.JPanel panelUno;
    private javax.swing.JSpinner sp_dpiValue;
    private javax.swing.JTextField txt_guardarPdf;
    private javax.swing.JTextField txt_imputmagen;
    private javax.swing.JTextField txt_juntarpdfDos;
    private javax.swing.JTextField txt_juntarpdfUno;
    private javax.swing.JTextField txt_namePDF;
    private javax.swing.JTextField txt_nombreImagen;
    private javax.swing.JTextField txt_outputImagen;
    private javax.swing.JTextField txt_rutaPdf;
    private javax.swing.JTextField txt_urlGuardadoPDF;
    private javax.swing.JTabbedPane vistaUno;
    // End of variables declaration//GEN-END:variables
}
